
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.VBox vbox7;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.HBox hbox5;

	private global::Gtk.VBox vboxPages;

	private global::Gtk.Label label4;

	private global::Gtk.HSeparator hseparator4;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Image imageTNVED;

	private global::Gtk.Button btnPageTNVED;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Image imageParty;

	private global::Gtk.Button btnPageParty;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Image imageTransport;

	private global::Gtk.Button btnPageTransport;

	private global::Gtk.Label spacing1;

	private global::Gtk.Label label2;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Image imagePackingList;

	private global::Gtk.Button btnPagePackingList;

	private global::Gtk.HBox hbox15;

	private global::Gtk.Image imageSpecification;

	private global::Gtk.Button btnPageSpecification;

	private global::Gtk.HBox hbox16;

	private global::Gtk.Image imageCMP;

	private global::Gtk.Button btnPageCMP;

	private global::Gtk.Label spacing2;

	private global::Gtk.Label label3;

	private global::Gtk.HSeparator hseparator3;

	private global::Gtk.HBox hbox14;

	private global::Gtk.Image imageOutput;

	private global::Gtk.Button btnPageOutput;

	private global::Gtk.Notebook stackPages;

	private global::Gtk.VBox vboxPageTNVED;

	private global::Gtk.HBox hbox17;

	private global::Gtk.Alignment alignment1;

	private global::Gtk.Label label5;

	private global::Gtk.FileChooserButton filechooserTNVED;

	private global::Gtk.Frame frameTNVED;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hboxTNVEDname;

	private global::Gtk.Label labelTNVEDname;

	private global::Gtk.ComboBox combTNVEDnames;

	private global::Gtk.HBox hboxTNVEDname2;

	private global::Gtk.Label labelTNVEDname2;

	private global::Gtk.ComboBox combTNVEDnames2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button btnNextTNVED;

	private global::Gtk.Label label7;

	private global::Gtk.VBox vboxPageParty;

	private global::Gtk.HBox hbox18;

	private global::Gtk.Alignment alignment2;

	private global::Gtk.Label label6;

	private global::Gtk.FileChooserButton filechooserParty;

	private global::Gtk.Frame framePartyList1;

	private global::Gtk.Alignment frame;

	private global::Gtk.VBox vbox9;

	private global::Gtk.HBox hboxTNVEDname1;

	private global::Gtk.Label labelTNVEDname1;

	private global::Gtk.ComboBox combPartyName;

	private global::Gtk.HBox hboxTNVEDname4;

	private global::Gtk.Label labelTNVEDname4;

	private global::Gtk.ComboBox combPartyNum;

	private global::Gtk.HBox hboxTNVEDname3;

	private global::Gtk.Label labelTNVEDname3;

	private global::Gtk.ComboBox combPartyAllCount;

	private global::Gtk.HBox hboxTNVEDname6;

	private global::Gtk.Label labelTNVEDname6;

	private global::Gtk.ComboBox combPartyCountByType;

	private global::Gtk.HBox hboxTNVEDname5;

	private global::Gtk.Label labelTNVEDname5;

	private global::Gtk.ComboBox combPartyCost;

	private global::Gtk.Frame framePartyList2;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hboxTNVEDname7;

	private global::Gtk.Label labelTNVEDname7;

	private global::Gtk.ComboBox combTNVEDnames1;

	private global::Gtk.HBox hboxTNVEDname8;

	private global::Gtk.Label labelTNVEDname8;

	private global::Gtk.ComboBox combTNVEDnames3;

	private global::Gtk.HBox hboxTNVEDname9;

	private global::Gtk.Label labelTNVEDname9;

	private global::Gtk.ComboBox combTNVEDnames4;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button btnNextTNVED1;

	private global::Gtk.Button button5;

	private global::Gtk.Label label8;

	private global::Gtk.VBox vboxPageTNVED2;

	private global::Gtk.HBox hbox20;

	private global::Gtk.Alignment alignment4;

	private global::Gtk.Label label10;

	private global::Gtk.FileChooserButton filechooserTransport;

	private global::Gtk.Frame frameTransport;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.VBox vboxTransport;

	private global::Gtk.HBox hboxTNVEDname10;

	private global::Gtk.Label labelDriver;

	private global::Gtk.ComboBox combDriver;

	private global::Gtk.HBox hboxTNVEDname11;

	private global::Gtk.Label labelCar;

	private global::Gtk.ComboBox combCar;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button btnNextTNVED3;

	private global::Gtk.Label label11;

	private global::Gtk.VBox vboxPageTransport;

	private global::Gtk.HBox hbox19;

	private global::Gtk.Alignment alignment3;

	private global::Gtk.Label labelTransport;

	private global::Gtk.FileChooserButton filechooserPackSave;

	private global::Gtk.Label label12;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button btnNextTNVED2;

	private global::Gtk.Button button6;

	private global::Gtk.Label label9;

	private global::Gtk.Label label13;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Товары");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		// Container child vbox7.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned();
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 205;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vboxPages = new global::Gtk.VBox();
		this.vboxPages.Name = "vboxPages";
		this.vboxPages.Spacing = 6;
		this.vboxPages.BorderWidth = ((uint)(7));
		// Container child vboxPages.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Sensitive = false;
		this.label4.Name = "label4";
		this.label4.Ypad = 3;
		this.label4.Xalign = 0F;
		this.label4.Yalign = 0F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Источники:");
		this.label4.UseMarkup = true;
		this.label4.SingleLineMode = true;
		this.vboxPages.Add(this.label4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.label4]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator();
		this.hseparator4.Name = "hseparator4";
		this.vboxPages.Add(this.hseparator4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.hseparator4]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.imageTNVED = new global::Gtk.Image();
		this.imageTNVED.Name = "imageTNVED";
		this.imageTNVED.Xalign = 0F;
		this.imageTNVED.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
		this.hbox9.Add(this.imageTNVED);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.imageTNVED]));
		w4.Position = 0;
		w4.Expand = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.btnPageTNVED = new global::Gtk.Button();
		this.btnPageTNVED.Name = "btnPageTNVED";
		this.btnPageTNVED.FocusOnClick = false;
		this.btnPageTNVED.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnPageTNVED.Label = global::Mono.Unix.Catalog.GetString("Коды ТН ВЭД");
		this.hbox9.Add(this.btnPageTNVED);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.btnPageTNVED]));
		w5.Position = 1;
		this.vboxPages.Add(this.hbox9);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.hbox9]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.imageParty = new global::Gtk.Image();
		this.imageParty.Name = "imageParty";
		this.imageParty.Xalign = 0F;
		this.imageParty.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-go-forward", global::Gtk.IconSize.Menu);
		this.hbox10.Add(this.imageParty);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.imageParty]));
		w7.Position = 0;
		w7.Expand = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.btnPageParty = new global::Gtk.Button();
		this.btnPageParty.Name = "btnPageParty";
		this.btnPageParty.FocusOnClick = false;
		this.btnPageParty.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnPageParty.Label = global::Mono.Unix.Catalog.GetString("Партия");
		this.hbox10.Add(this.btnPageParty);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.btnPageParty]));
		w8.Position = 1;
		this.vboxPages.Add(this.hbox10);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.hbox10]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.imageTransport = new global::Gtk.Image();
		this.imageTransport.Name = "imageTransport";
		this.imageTransport.Xalign = 0F;
		this.imageTransport.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
		this.hbox11.Add(this.imageTransport);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.imageTransport]));
		w10.Position = 0;
		w10.Expand = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.btnPageTransport = new global::Gtk.Button();
		this.btnPageTransport.Name = "btnPageTransport";
		this.btnPageTransport.FocusOnClick = false;
		this.btnPageTransport.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnPageTransport.Label = global::Mono.Unix.Catalog.GetString("Транспорт");
		this.hbox11.Add(this.btnPageTransport);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.btnPageTransport]));
		w11.Position = 1;
		this.vboxPages.Add(this.hbox11);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.hbox11]));
		w12.Position = 4;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.spacing1 = new global::Gtk.Label();
		this.spacing1.Name = "spacing1";
		this.vboxPages.Add(this.spacing1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.spacing1]));
		w13.Position = 5;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Sensitive = false;
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Шаблоны:");
		this.label2.UseMarkup = true;
		this.label2.SingleLineMode = true;
		this.vboxPages.Add(this.label2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.label2]));
		w14.Position = 6;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.Name = "hseparator2";
		this.vboxPages.Add(this.hseparator2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.hseparator2]));
		w15.Position = 7;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.imagePackingList = new global::Gtk.Image();
		this.imagePackingList.Sensitive = false;
		this.imagePackingList.Name = "imagePackingList";
		this.imagePackingList.Xalign = 0F;
		this.imagePackingList.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
		this.hbox12.Add(this.imagePackingList);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.imagePackingList]));
		w16.Position = 0;
		w16.Expand = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.btnPagePackingList = new global::Gtk.Button();
		this.btnPagePackingList.Sensitive = false;
		this.btnPagePackingList.Name = "btnPagePackingList";
		this.btnPagePackingList.FocusOnClick = false;
		this.btnPagePackingList.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnPagePackingList.Label = global::Mono.Unix.Catalog.GetString("Упаковочный лист");
		this.hbox12.Add(this.btnPagePackingList);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.btnPagePackingList]));
		w17.Position = 1;
		this.vboxPages.Add(this.hbox12);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.hbox12]));
		w18.Position = 8;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.imageSpecification = new global::Gtk.Image();
		this.imageSpecification.Sensitive = false;
		this.imageSpecification.Name = "imageSpecification";
		this.imageSpecification.Xalign = 0F;
		this.imageSpecification.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
		this.hbox15.Add(this.imageSpecification);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.imageSpecification]));
		w19.Position = 0;
		w19.Expand = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.btnPageSpecification = new global::Gtk.Button();
		this.btnPageSpecification.Sensitive = false;
		this.btnPageSpecification.Name = "btnPageSpecification";
		this.btnPageSpecification.FocusOnClick = false;
		this.btnPageSpecification.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnPageSpecification.Label = global::Mono.Unix.Catalog.GetString("Спецификация");
		this.hbox15.Add(this.btnPageSpecification);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.btnPageSpecification]));
		w20.Position = 1;
		this.vboxPages.Add(this.hbox15);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.hbox15]));
		w21.Position = 9;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.imageCMP = new global::Gtk.Image();
		this.imageCMP.Sensitive = false;
		this.imageCMP.Name = "imageCMP";
		this.imageCMP.Xalign = 0F;
		this.imageCMP.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
		this.hbox16.Add(this.imageCMP);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.imageCMP]));
		w22.Position = 0;
		w22.Expand = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.btnPageCMP = new global::Gtk.Button();
		this.btnPageCMP.Sensitive = false;
		this.btnPageCMP.Name = "btnPageCMP";
		this.btnPageCMP.FocusOnClick = false;
		this.btnPageCMP.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnPageCMP.Label = global::Mono.Unix.Catalog.GetString("СМР");
		this.hbox16.Add(this.btnPageCMP);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.btnPageCMP]));
		w23.Position = 1;
		this.vboxPages.Add(this.hbox16);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.hbox16]));
		w24.Position = 10;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.spacing2 = new global::Gtk.Label();
		this.spacing2.Name = "spacing2";
		this.vboxPages.Add(this.spacing2);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.spacing2]));
		w25.Position = 11;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Sensitive = false;
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Результат:");
		this.label3.UseMarkup = true;
		this.label3.SingleLineMode = true;
		this.vboxPages.Add(this.label3);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.label3]));
		w26.Position = 12;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator();
		this.hseparator3.Name = "hseparator3";
		this.vboxPages.Add(this.hseparator3);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.hseparator3]));
		w27.Position = 13;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vboxPages.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.imageOutput = new global::Gtk.Image();
		this.imageOutput.Sensitive = false;
		this.imageOutput.Name = "imageOutput";
		this.imageOutput.Xalign = 0F;
		this.imageOutput.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
		this.hbox14.Add(this.imageOutput);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.imageOutput]));
		w28.Position = 0;
		w28.Expand = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.btnPageOutput = new global::Gtk.Button();
		this.btnPageOutput.Sensitive = false;
		this.btnPageOutput.Name = "btnPageOutput";
		this.btnPageOutput.FocusOnClick = false;
		this.btnPageOutput.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnPageOutput.Label = global::Mono.Unix.Catalog.GetString("Выходные файлы");
		this.hbox14.Add(this.btnPageOutput);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.btnPageOutput]));
		w29.Position = 1;
		this.vboxPages.Add(this.hbox14);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vboxPages[this.hbox14]));
		w30.Position = 14;
		w30.Expand = false;
		w30.Fill = false;
		this.hbox5.Add(this.vboxPages);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vboxPages]));
		w31.Position = 0;
		this.hpaned1.Add(this.hbox5);
		global::Gtk.Paned.PanedChild w32 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.hbox5]));
		w32.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.stackPages = new global::Gtk.Notebook();
		this.stackPages.CanFocus = true;
		this.stackPages.Name = "stackPages";
		this.stackPages.CurrentPage = 3;
		this.stackPages.ShowBorder = false;
		// Container child stackPages.Gtk.Notebook+NotebookChild
		this.vboxPageTNVED = new global::Gtk.VBox();
		this.vboxPageTNVED.Name = "vboxPageTNVED";
		this.vboxPageTNVED.Spacing = 6;
		this.vboxPageTNVED.BorderWidth = ((uint)(4));
		// Container child vboxPageTNVED.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.alignment1.LeftPadding = ((uint)(4));
		// Container child alignment1.Gtk.Container+ContainerChild
		this.label5 = new global::Gtk.Label();
		this.label5.WidthRequest = 200;
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Файл \"Коды ТН ВЭД\":");
		this.alignment1.Add(this.label5);
		this.hbox17.Add(this.alignment1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.alignment1]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.filechooserTNVED = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Коды ТН ВЭД\n"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserTNVED.Name = "filechooserTNVED";
		this.hbox17.Add(this.filechooserTNVED);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.filechooserTNVED]));
		w35.Position = 1;
		this.vboxPageTNVED.Add(this.hbox17);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED[this.hbox17]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vboxPageTNVED.Gtk.Box+BoxChild
		this.frameTNVED = new global::Gtk.Frame();
		this.frameTNVED.Sensitive = false;
		this.frameTNVED.Name = "frameTNVED";
		// Container child frameTNVED.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.BorderWidth = ((uint)(2));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hboxTNVEDname = new global::Gtk.HBox();
		this.hboxTNVEDname.Name = "hboxTNVEDname";
		this.hboxTNVEDname.Spacing = 6;
		// Container child hboxTNVEDname.Gtk.Box+BoxChild
		this.labelTNVEDname = new global::Gtk.Label();
		this.labelTNVEDname.WidthRequest = 200;
		this.labelTNVEDname.Name = "labelTNVEDname";
		this.labelTNVEDname.Xalign = 0F;
		this.labelTNVEDname.LabelProp = global::Mono.Unix.Catalog.GetString("Номер отправления:");
		this.hboxTNVEDname.Add(this.labelTNVEDname);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname[this.labelTNVEDname]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hboxTNVEDname.Gtk.Box+BoxChild
		this.combTNVEDnames = global::Gtk.ComboBox.NewText();
		this.combTNVEDnames.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combTNVEDnames.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combTNVEDnames.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combTNVEDnames.Name = "combTNVEDnames";
		this.combTNVEDnames.Active = 0;
		this.hboxTNVEDname.Add(this.combTNVEDnames);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname[this.combTNVEDnames]));
		w38.Position = 1;
		this.vbox1.Add(this.hboxTNVEDname);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxTNVEDname]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hboxTNVEDname2 = new global::Gtk.HBox();
		this.hboxTNVEDname2.Name = "hboxTNVEDname2";
		this.hboxTNVEDname2.Spacing = 6;
		// Container child hboxTNVEDname2.Gtk.Box+BoxChild
		this.labelTNVEDname2 = new global::Gtk.Label();
		this.labelTNVEDname2.WidthRequest = 200;
		this.labelTNVEDname2.Name = "labelTNVEDname2";
		this.labelTNVEDname2.Xalign = 0F;
		this.labelTNVEDname2.LabelProp = global::Mono.Unix.Catalog.GetString("Код товара:");
		this.hboxTNVEDname2.Add(this.labelTNVEDname2);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname2[this.labelTNVEDname2]));
		w40.Position = 0;
		w40.Expand = false;
		w40.Fill = false;
		// Container child hboxTNVEDname2.Gtk.Box+BoxChild
		this.combTNVEDnames2 = global::Gtk.ComboBox.NewText();
		this.combTNVEDnames2.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combTNVEDnames2.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combTNVEDnames2.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combTNVEDnames2.Name = "combTNVEDnames2";
		this.combTNVEDnames2.Active = 1;
		this.hboxTNVEDname2.Add(this.combTNVEDnames2);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname2[this.combTNVEDnames2]));
		w41.Position = 1;
		this.vbox1.Add(this.hboxTNVEDname2);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxTNVEDname2]));
		w42.Position = 1;
		w42.Expand = false;
		w42.Fill = false;
		this.GtkAlignment.Add(this.vbox1);
		this.frameTNVED.Add(this.GtkAlignment);
		this.vboxPageTNVED.Add(this.frameTNVED);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED[this.frameTNVED]));
		w45.Position = 1;
		// Container child vboxPageTNVED.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnNextTNVED = new global::Gtk.Button();
		this.btnNextTNVED.WidthRequest = 80;
		this.btnNextTNVED.CanFocus = true;
		this.btnNextTNVED.Name = "btnNextTNVED";
		this.btnNextTNVED.UseUnderline = true;
		this.btnNextTNVED.Label = global::Mono.Unix.Catalog.GetString("Далее");
		this.hbox3.Add(this.btnNextTNVED);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnNextTNVED]));
		w46.PackType = ((global::Gtk.PackType)(1));
		w46.Position = 0;
		w46.Expand = false;
		w46.Fill = false;
		this.vboxPageTNVED.Add(this.hbox3);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED[this.hbox3]));
		w47.Position = 2;
		w47.Expand = false;
		w47.Fill = false;
		this.stackPages.Add(this.vboxPageTNVED);
		// Notebook tab
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("page1");
		this.stackPages.SetTabLabel(this.vboxPageTNVED, this.label7);
		this.label7.ShowAll();
		// Container child stackPages.Gtk.Notebook+NotebookChild
		this.vboxPageParty = new global::Gtk.VBox();
		this.vboxPageParty.Name = "vboxPageParty";
		this.vboxPageParty.Spacing = 6;
		this.vboxPageParty.BorderWidth = ((uint)(4));
		// Container child vboxPageParty.Gtk.Box+BoxChild
		this.hbox18 = new global::Gtk.HBox();
		this.hbox18.Name = "hbox18";
		this.hbox18.Spacing = 6;
		// Container child hbox18.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.alignment2.LeftPadding = ((uint)(4));
		// Container child alignment2.Gtk.Container+ContainerChild
		this.label6 = new global::Gtk.Label();
		this.label6.WidthRequest = 200;
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Файл \"Партия\":");
		this.alignment2.Add(this.label6);
		this.hbox18.Add(this.alignment2);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.alignment2]));
		w50.Position = 0;
		w50.Expand = false;
		w50.Fill = false;
		// Container child hbox18.Gtk.Box+BoxChild
		this.filechooserParty = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Коды ТН ВЭД\n"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserParty.Name = "filechooserParty";
		this.hbox18.Add(this.filechooserParty);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.filechooserParty]));
		w51.Position = 1;
		this.vboxPageParty.Add(this.hbox18);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vboxPageParty[this.hbox18]));
		w52.Position = 0;
		w52.Expand = false;
		w52.Fill = false;
		// Container child vboxPageParty.Gtk.Box+BoxChild
		this.framePartyList1 = new global::Gtk.Frame();
		this.framePartyList1.Sensitive = false;
		this.framePartyList1.Name = "framePartyList1";
		// Container child framePartyList1.Gtk.Container+ContainerChild
		this.frame = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.frame.Name = "frame";
		this.frame.BorderWidth = ((uint)(2));
		// Container child frame.Gtk.Container+ContainerChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hboxTNVEDname1 = new global::Gtk.HBox();
		this.hboxTNVEDname1.Name = "hboxTNVEDname1";
		this.hboxTNVEDname1.Spacing = 6;
		// Container child hboxTNVEDname1.Gtk.Box+BoxChild
		this.labelTNVEDname1 = new global::Gtk.Label();
		this.labelTNVEDname1.WidthRequest = 200;
		this.labelTNVEDname1.Name = "labelTNVEDname1";
		this.labelTNVEDname1.Xalign = 0F;
		this.labelTNVEDname1.LabelProp = global::Mono.Unix.Catalog.GetString("Наименование товара:");
		this.hboxTNVEDname1.Add(this.labelTNVEDname1);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname1[this.labelTNVEDname1]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child hboxTNVEDname1.Gtk.Box+BoxChild
		this.combPartyName = global::Gtk.ComboBox.NewText();
		this.combPartyName.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combPartyName.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combPartyName.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combPartyName.AppendText("");
		this.combPartyName.Name = "combPartyName";
		this.combPartyName.Active = 0;
		this.hboxTNVEDname1.Add(this.combPartyName);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname1[this.combPartyName]));
		w54.Position = 1;
		this.vbox9.Add(this.hboxTNVEDname1);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hboxTNVEDname1]));
		w55.Position = 0;
		w55.Expand = false;
		w55.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hboxTNVEDname4 = new global::Gtk.HBox();
		this.hboxTNVEDname4.Name = "hboxTNVEDname4";
		this.hboxTNVEDname4.Spacing = 6;
		// Container child hboxTNVEDname4.Gtk.Box+BoxChild
		this.labelTNVEDname4 = new global::Gtk.Label();
		this.labelTNVEDname4.WidthRequest = 200;
		this.labelTNVEDname4.Name = "labelTNVEDname4";
		this.labelTNVEDname4.Xalign = 0F;
		this.labelTNVEDname4.LabelProp = global::Mono.Unix.Catalog.GetString("Номер отправления:");
		this.hboxTNVEDname4.Add(this.labelTNVEDname4);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname4[this.labelTNVEDname4]));
		w56.Position = 0;
		w56.Expand = false;
		w56.Fill = false;
		// Container child hboxTNVEDname4.Gtk.Box+BoxChild
		this.combPartyNum = global::Gtk.ComboBox.NewText();
		this.combPartyNum.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combPartyNum.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combPartyNum.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combPartyNum.AppendText("");
		this.combPartyNum.Name = "combPartyNum";
		this.combPartyNum.Active = 2;
		this.hboxTNVEDname4.Add(this.combPartyNum);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname4[this.combPartyNum]));
		w57.Position = 1;
		this.vbox9.Add(this.hboxTNVEDname4);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hboxTNVEDname4]));
		w58.Position = 1;
		w58.Expand = false;
		w58.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hboxTNVEDname3 = new global::Gtk.HBox();
		this.hboxTNVEDname3.Name = "hboxTNVEDname3";
		this.hboxTNVEDname3.Spacing = 6;
		// Container child hboxTNVEDname3.Gtk.Box+BoxChild
		this.labelTNVEDname3 = new global::Gtk.Label();
		this.labelTNVEDname3.WidthRequest = 200;
		this.labelTNVEDname3.Name = "labelTNVEDname3";
		this.labelTNVEDname3.Xalign = 0F;
		this.labelTNVEDname3.LabelProp = global::Mono.Unix.Catalog.GetString("Суммарное количество вложений:");
		this.hboxTNVEDname3.Add(this.labelTNVEDname3);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname3[this.labelTNVEDname3]));
		w59.Position = 0;
		w59.Expand = false;
		w59.Fill = false;
		// Container child hboxTNVEDname3.Gtk.Box+BoxChild
		this.combPartyAllCount = global::Gtk.ComboBox.NewText();
		this.combPartyAllCount.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combPartyAllCount.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combPartyAllCount.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combPartyAllCount.Name = "combPartyAllCount";
		this.combPartyAllCount.Active = 1;
		this.hboxTNVEDname3.Add(this.combPartyAllCount);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname3[this.combPartyAllCount]));
		w60.Position = 1;
		this.vbox9.Add(this.hboxTNVEDname3);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hboxTNVEDname3]));
		w61.Position = 2;
		w61.Expand = false;
		w61.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hboxTNVEDname6 = new global::Gtk.HBox();
		this.hboxTNVEDname6.Name = "hboxTNVEDname6";
		this.hboxTNVEDname6.Spacing = 6;
		// Container child hboxTNVEDname6.Gtk.Box+BoxChild
		this.labelTNVEDname6 = new global::Gtk.Label();
		this.labelTNVEDname6.WidthRequest = 200;
		this.labelTNVEDname6.Name = "labelTNVEDname6";
		this.labelTNVEDname6.Xalign = 0F;
		this.labelTNVEDname6.LabelProp = global::Mono.Unix.Catalog.GetString("Количество объектов в посылке:");
		this.hboxTNVEDname6.Add(this.labelTNVEDname6);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname6[this.labelTNVEDname6]));
		w62.Position = 0;
		w62.Expand = false;
		w62.Fill = false;
		// Container child hboxTNVEDname6.Gtk.Box+BoxChild
		this.combPartyCountByType = global::Gtk.ComboBox.NewText();
		this.combPartyCountByType.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combPartyCountByType.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combPartyCountByType.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combPartyCountByType.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.combPartyCountByType.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.combPartyCountByType.AppendText("");
		this.combPartyCountByType.Name = "combPartyCountByType";
		this.combPartyCountByType.Active = 3;
		this.hboxTNVEDname6.Add(this.combPartyCountByType);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname6[this.combPartyCountByType]));
		w63.Position = 1;
		this.vbox9.Add(this.hboxTNVEDname6);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hboxTNVEDname6]));
		w64.Position = 3;
		w64.Expand = false;
		w64.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hboxTNVEDname5 = new global::Gtk.HBox();
		this.hboxTNVEDname5.Name = "hboxTNVEDname5";
		this.hboxTNVEDname5.Spacing = 6;
		// Container child hboxTNVEDname5.Gtk.Box+BoxChild
		this.labelTNVEDname5 = new global::Gtk.Label();
		this.labelTNVEDname5.WidthRequest = 200;
		this.labelTNVEDname5.Name = "labelTNVEDname5";
		this.labelTNVEDname5.Xalign = 0F;
		this.labelTNVEDname5.LabelProp = global::Mono.Unix.Catalog.GetString("Цена:");
		this.hboxTNVEDname5.Add(this.labelTNVEDname5);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname5[this.labelTNVEDname5]));
		w65.Position = 0;
		w65.Expand = false;
		w65.Fill = false;
		// Container child hboxTNVEDname5.Gtk.Box+BoxChild
		this.combPartyCost = global::Gtk.ComboBox.NewText();
		this.combPartyCost.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combPartyCost.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combPartyCost.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combPartyCost.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.combPartyCost.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.combPartyCost.AppendText("");
		this.combPartyCost.Name = "combPartyCost";
		this.combPartyCost.Active = 3;
		this.hboxTNVEDname5.Add(this.combPartyCost);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname5[this.combPartyCost]));
		w66.Position = 1;
		this.vbox9.Add(this.hboxTNVEDname5);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hboxTNVEDname5]));
		w67.Position = 4;
		w67.Expand = false;
		w67.Fill = false;
		this.frame.Add(this.vbox9);
		this.framePartyList1.Add(this.frame);
		this.vboxPageParty.Add(this.framePartyList1);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vboxPageParty[this.framePartyList1]));
		w70.Position = 1;
		// Container child vboxPageParty.Gtk.Box+BoxChild
		this.framePartyList2 = new global::Gtk.Frame();
		this.framePartyList2.Sensitive = false;
		this.framePartyList2.Name = "framePartyList2";
		// Container child framePartyList2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.BorderWidth = ((uint)(2));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hboxTNVEDname7 = new global::Gtk.HBox();
		this.hboxTNVEDname7.Name = "hboxTNVEDname7";
		this.hboxTNVEDname7.Spacing = 6;
		// Container child hboxTNVEDname7.Gtk.Box+BoxChild
		this.labelTNVEDname7 = new global::Gtk.Label();
		this.labelTNVEDname7.WidthRequest = 200;
		this.labelTNVEDname7.Name = "labelTNVEDname7";
		this.labelTNVEDname7.Xalign = 0F;
		this.labelTNVEDname7.LabelProp = global::Mono.Unix.Catalog.GetString("Номер мешка:");
		this.hboxTNVEDname7.Add(this.labelTNVEDname7);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname7[this.labelTNVEDname7]));
		w71.Position = 0;
		w71.Expand = false;
		w71.Fill = false;
		// Container child hboxTNVEDname7.Gtk.Box+BoxChild
		this.combTNVEDnames1 = global::Gtk.ComboBox.NewText();
		this.combTNVEDnames1.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combTNVEDnames1.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combTNVEDnames1.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combTNVEDnames1.Name = "combTNVEDnames1";
		this.combTNVEDnames1.Active = 0;
		this.hboxTNVEDname7.Add(this.combTNVEDnames1);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname7[this.combTNVEDnames1]));
		w72.Position = 1;
		this.vbox2.Add(this.hboxTNVEDname7);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxTNVEDname7]));
		w73.Position = 0;
		w73.Expand = false;
		w73.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hboxTNVEDname8 = new global::Gtk.HBox();
		this.hboxTNVEDname8.Name = "hboxTNVEDname8";
		this.hboxTNVEDname8.Spacing = 6;
		// Container child hboxTNVEDname8.Gtk.Box+BoxChild
		this.labelTNVEDname8 = new global::Gtk.Label();
		this.labelTNVEDname8.WidthRequest = 200;
		this.labelTNVEDname8.Name = "labelTNVEDname8";
		this.labelTNVEDname8.Xalign = 0F;
		this.labelTNVEDname8.LabelProp = global::Mono.Unix.Catalog.GetString("Наименование отправления:");
		this.hboxTNVEDname8.Add(this.labelTNVEDname8);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname8[this.labelTNVEDname8]));
		w74.Position = 0;
		w74.Expand = false;
		w74.Fill = false;
		// Container child hboxTNVEDname8.Gtk.Box+BoxChild
		this.combTNVEDnames3 = global::Gtk.ComboBox.NewText();
		this.combTNVEDnames3.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combTNVEDnames3.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combTNVEDnames3.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combTNVEDnames3.Name = "combTNVEDnames3";
		this.combTNVEDnames3.Active = 1;
		this.hboxTNVEDname8.Add(this.combTNVEDnames3);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname8[this.combTNVEDnames3]));
		w75.Position = 1;
		this.vbox2.Add(this.hboxTNVEDname8);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxTNVEDname8]));
		w76.Position = 1;
		w76.Expand = false;
		w76.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hboxTNVEDname9 = new global::Gtk.HBox();
		this.hboxTNVEDname9.Name = "hboxTNVEDname9";
		this.hboxTNVEDname9.Spacing = 6;
		// Container child hboxTNVEDname9.Gtk.Box+BoxChild
		this.labelTNVEDname9 = new global::Gtk.Label();
		this.labelTNVEDname9.WidthRequest = 200;
		this.labelTNVEDname9.Name = "labelTNVEDname9";
		this.labelTNVEDname9.Xalign = 0F;
		this.labelTNVEDname9.LabelProp = global::Mono.Unix.Catalog.GetString("Вес:");
		this.hboxTNVEDname9.Add(this.labelTNVEDname9);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname9[this.labelTNVEDname9]));
		w77.Position = 0;
		w77.Expand = false;
		w77.Fill = false;
		// Container child hboxTNVEDname9.Gtk.Box+BoxChild
		this.combTNVEDnames4 = global::Gtk.ComboBox.NewText();
		this.combTNVEDnames4.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combTNVEDnames4.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combTNVEDnames4.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combTNVEDnames4.Name = "combTNVEDnames4";
		this.combTNVEDnames4.Active = 1;
		this.hboxTNVEDname9.Add(this.combTNVEDnames4);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname9[this.combTNVEDnames4]));
		w78.Position = 1;
		this.vbox2.Add(this.hboxTNVEDname9);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxTNVEDname9]));
		w79.Position = 2;
		w79.Expand = false;
		w79.Fill = false;
		this.GtkAlignment1.Add(this.vbox2);
		this.framePartyList2.Add(this.GtkAlignment1);
		this.vboxPageParty.Add(this.framePartyList2);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vboxPageParty[this.framePartyList2]));
		w82.Position = 2;
		// Container child vboxPageParty.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnNextTNVED1 = new global::Gtk.Button();
		this.btnNextTNVED1.WidthRequest = 80;
		this.btnNextTNVED1.CanFocus = true;
		this.btnNextTNVED1.Name = "btnNextTNVED1";
		this.btnNextTNVED1.UseUnderline = true;
		this.btnNextTNVED1.Label = global::Mono.Unix.Catalog.GetString("Далее");
		this.hbox4.Add(this.btnNextTNVED1);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnNextTNVED1]));
		w83.PackType = ((global::Gtk.PackType)(1));
		w83.Position = 0;
		w83.Expand = false;
		w83.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.WidthRequest = 80;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Назад");
		this.hbox4.Add(this.button5);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button5]));
		w84.PackType = ((global::Gtk.PackType)(1));
		w84.Position = 1;
		w84.Expand = false;
		w84.Fill = false;
		this.vboxPageParty.Add(this.hbox4);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vboxPageParty[this.hbox4]));
		w85.Position = 3;
		w85.Expand = false;
		w85.Fill = false;
		this.stackPages.Add(this.vboxPageParty);
		global::Gtk.Notebook.NotebookChild w86 = ((global::Gtk.Notebook.NotebookChild)(this.stackPages[this.vboxPageParty]));
		w86.Position = 1;
		// Notebook tab
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("page2");
		this.stackPages.SetTabLabel(this.vboxPageParty, this.label8);
		this.label8.ShowAll();
		// Container child stackPages.Gtk.Notebook+NotebookChild
		this.vboxPageTNVED2 = new global::Gtk.VBox();
		this.vboxPageTNVED2.Name = "vboxPageTNVED2";
		this.vboxPageTNVED2.Spacing = 6;
		this.vboxPageTNVED2.BorderWidth = ((uint)(4));
		// Container child vboxPageTNVED2.Gtk.Box+BoxChild
		this.hbox20 = new global::Gtk.HBox();
		this.hbox20.Name = "hbox20";
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment4.Name = "alignment4";
		this.alignment4.LeftPadding = ((uint)(4));
		// Container child alignment4.Gtk.Container+ContainerChild
		this.label10 = new global::Gtk.Label();
		this.label10.WidthRequest = 200;
		this.label10.Name = "label10";
		this.label10.Xalign = 0F;
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Файл \"Транспорт\":");
		this.alignment4.Add(this.label10);
		this.hbox20.Add(this.alignment4);
		global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.alignment4]));
		w88.Position = 0;
		w88.Expand = false;
		w88.Fill = false;
		// Container child hbox20.Gtk.Box+BoxChild
		this.filechooserTransport = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Коды ТН ВЭД\n"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserTransport.Name = "filechooserTransport";
		this.hbox20.Add(this.filechooserTransport);
		global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.filechooserTransport]));
		w89.Position = 1;
		this.vboxPageTNVED2.Add(this.hbox20);
		global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED2[this.hbox20]));
		w90.Position = 0;
		w90.Expand = false;
		w90.Fill = false;
		// Container child vboxPageTNVED2.Gtk.Box+BoxChild
		this.frameTransport = new global::Gtk.Frame();
		this.frameTransport.Sensitive = false;
		this.frameTransport.Name = "frameTransport";
		// Container child frameTransport.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.BorderWidth = ((uint)(2));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vboxTransport = new global::Gtk.VBox();
		this.vboxTransport.Name = "vboxTransport";
		this.vboxTransport.Spacing = 6;
		// Container child vboxTransport.Gtk.Box+BoxChild
		this.hboxTNVEDname10 = new global::Gtk.HBox();
		this.hboxTNVEDname10.Name = "hboxTNVEDname10";
		this.hboxTNVEDname10.Spacing = 6;
		// Container child hboxTNVEDname10.Gtk.Box+BoxChild
		this.labelDriver = new global::Gtk.Label();
		this.labelDriver.WidthRequest = 200;
		this.labelDriver.Name = "labelDriver";
		this.labelDriver.Xalign = 0F;
		this.labelDriver.LabelProp = global::Mono.Unix.Catalog.GetString("Водитель:");
		this.hboxTNVEDname10.Add(this.labelDriver);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname10[this.labelDriver]));
		w91.Position = 0;
		w91.Expand = false;
		w91.Fill = false;
		// Container child hboxTNVEDname10.Gtk.Box+BoxChild
		this.combDriver = global::Gtk.ComboBox.NewText();
		this.combDriver.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combDriver.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combDriver.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combDriver.Name = "combDriver";
		this.combDriver.Active = 0;
		this.hboxTNVEDname10.Add(this.combDriver);
		global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname10[this.combDriver]));
		w92.Position = 1;
		this.vboxTransport.Add(this.hboxTNVEDname10);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vboxTransport[this.hboxTNVEDname10]));
		w93.Position = 0;
		w93.Expand = false;
		w93.Fill = false;
		// Container child vboxTransport.Gtk.Box+BoxChild
		this.hboxTNVEDname11 = new global::Gtk.HBox();
		this.hboxTNVEDname11.Name = "hboxTNVEDname11";
		this.hboxTNVEDname11.Spacing = 6;
		// Container child hboxTNVEDname11.Gtk.Box+BoxChild
		this.labelCar = new global::Gtk.Label();
		this.labelCar.WidthRequest = 200;
		this.labelCar.Name = "labelCar";
		this.labelCar.Xalign = 0F;
		this.labelCar.LabelProp = global::Mono.Unix.Catalog.GetString("Автомобиль:");
		this.hboxTNVEDname11.Add(this.labelCar);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname11[this.labelCar]));
		w94.Position = 0;
		w94.Expand = false;
		w94.Fill = false;
		// Container child hboxTNVEDname11.Gtk.Box+BoxChild
		this.combCar = global::Gtk.ComboBox.NewText();
		this.combCar.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combCar.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combCar.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combCar.Name = "combCar";
		this.combCar.Active = 1;
		this.hboxTNVEDname11.Add(this.combCar);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname11[this.combCar]));
		w95.Position = 1;
		this.vboxTransport.Add(this.hboxTNVEDname11);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vboxTransport[this.hboxTNVEDname11]));
		w96.Position = 1;
		w96.Expand = false;
		w96.Fill = false;
		this.GtkAlignment2.Add(this.vboxTransport);
		this.frameTransport.Add(this.GtkAlignment2);
		this.vboxPageTNVED2.Add(this.frameTransport);
		global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED2[this.frameTransport]));
		w99.Position = 1;
		// Container child vboxPageTNVED2.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.btnNextTNVED3 = new global::Gtk.Button();
		this.btnNextTNVED3.WidthRequest = 80;
		this.btnNextTNVED3.CanFocus = true;
		this.btnNextTNVED3.Name = "btnNextTNVED3";
		this.btnNextTNVED3.UseUnderline = true;
		this.btnNextTNVED3.Label = global::Mono.Unix.Catalog.GetString("Далее");
		this.hbox7.Add(this.btnNextTNVED3);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnNextTNVED3]));
		w100.PackType = ((global::Gtk.PackType)(1));
		w100.Position = 0;
		w100.Expand = false;
		w100.Fill = false;
		this.vboxPageTNVED2.Add(this.hbox7);
		global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED2[this.hbox7]));
		w101.Position = 2;
		w101.Expand = false;
		w101.Fill = false;
		this.stackPages.Add(this.vboxPageTNVED2);
		global::Gtk.Notebook.NotebookChild w102 = ((global::Gtk.Notebook.NotebookChild)(this.stackPages[this.vboxPageTNVED2]));
		w102.Position = 2;
		// Notebook tab
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("page4");
		this.stackPages.SetTabLabel(this.vboxPageTNVED2, this.label11);
		this.label11.ShowAll();
		// Container child stackPages.Gtk.Notebook+NotebookChild
		this.vboxPageTransport = new global::Gtk.VBox();
		this.vboxPageTransport.Name = "vboxPageTransport";
		this.vboxPageTransport.Spacing = 6;
		this.vboxPageTransport.BorderWidth = ((uint)(4));
		// Container child vboxPageTransport.Gtk.Box+BoxChild
		this.hbox19 = new global::Gtk.HBox();
		this.hbox19.Name = "hbox19";
		this.hbox19.Spacing = 6;
		// Container child hbox19.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		this.alignment3.LeftPadding = ((uint)(4));
		// Container child alignment3.Gtk.Container+ContainerChild
		this.labelTransport = new global::Gtk.Label();
		this.labelTransport.WidthRequest = 200;
		this.labelTransport.Name = "labelTransport";
		this.labelTransport.Xalign = 0F;
		this.labelTransport.LabelProp = global::Mono.Unix.Catalog.GetString("Сохранить \"Упаковочный лист\" как:");
		this.alignment3.Add(this.labelTransport);
		this.hbox19.Add(this.alignment3);
		global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.alignment3]));
		w104.Position = 0;
		w104.Expand = false;
		w104.Fill = false;
		// Container child hbox19.Gtk.Box+BoxChild
		this.filechooserPackSave = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserPackSave.Name = "filechooserPackSave";
		this.filechooserPackSave.LocalOnly = false;
		this.filechooserPackSave.ShowHidden = true;
		this.filechooserPackSave.DoOverwriteConfirmation = true;
		this.hbox19.Add(this.filechooserPackSave);
		global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.filechooserPackSave]));
		w105.Position = 1;
		this.vboxPageTransport.Add(this.hbox19);
		global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.vboxPageTransport[this.hbox19]));
		w106.Position = 0;
		w106.Expand = false;
		w106.Fill = false;
		// Container child vboxPageTransport.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.vboxPageTransport.Add(this.label12);
		global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.vboxPageTransport[this.label12]));
		w107.Position = 1;
		// Container child vboxPageTransport.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btnNextTNVED2 = new global::Gtk.Button();
		this.btnNextTNVED2.WidthRequest = 80;
		this.btnNextTNVED2.Sensitive = false;
		this.btnNextTNVED2.CanFocus = true;
		this.btnNextTNVED2.Name = "btnNextTNVED2";
		this.btnNextTNVED2.UseUnderline = true;
		this.btnNextTNVED2.Label = global::Mono.Unix.Catalog.GetString("Далее");
		this.hbox6.Add(this.btnNextTNVED2);
		global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnNextTNVED2]));
		w108.PackType = ((global::Gtk.PackType)(1));
		w108.Position = 0;
		w108.Expand = false;
		w108.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.WidthRequest = 80;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Назад");
		this.hbox6.Add(this.button6);
		global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.button6]));
		w109.PackType = ((global::Gtk.PackType)(1));
		w109.Position = 1;
		w109.Expand = false;
		w109.Fill = false;
		this.vboxPageTransport.Add(this.hbox6);
		global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vboxPageTransport[this.hbox6]));
		w110.Position = 2;
		w110.Expand = false;
		w110.Fill = false;
		this.stackPages.Add(this.vboxPageTransport);
		global::Gtk.Notebook.NotebookChild w111 = ((global::Gtk.Notebook.NotebookChild)(this.stackPages[this.vboxPageTransport]));
		w111.Position = 3;
		// Notebook tab
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("page3");
		this.stackPages.SetTabLabel(this.vboxPageTransport, this.label9);
		this.label9.ShowAll();
		// Notebook tab
		global::Gtk.Label w112 = new global::Gtk.Label();
		w112.Visible = true;
		this.stackPages.Add(w112);
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("page5");
		this.stackPages.SetTabLabel(w112, this.label13);
		this.label13.ShowAll();
		this.hpaned1.Add(this.stackPages);
		global::Gtk.Paned.PanedChild w113 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.stackPages]));
		w113.Shrink = false;
		this.vbox7.Add(this.hpaned1);
		global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hpaned1]));
		w114.Position = 1;
		this.Add(this.vbox7);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 847;
		this.DefaultHeight = 577;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.filechooserTNVED.SelectionChanged += new global::System.EventHandler(this.onTNVEDselected);
		this.btnNextTNVED.Clicked += new global::System.EventHandler(this.OnNext);
		this.filechooserParty.SelectionChanged += new global::System.EventHandler(this.OnPartySelected);
		this.button5.Clicked += new global::System.EventHandler(this.OnBack);
		this.btnNextTNVED1.Clicked += new global::System.EventHandler(this.OnNext);
		this.filechooserTransport.SelectionChanged += new global::System.EventHandler(this.OnTransportSelected);
		this.btnNextTNVED3.Clicked += new global::System.EventHandler(this.OnNext);
		this.filechooserPackSave.Added += new global::Gtk.AddedHandler(this.OnPackSaveAs);
		this.button6.Clicked += new global::System.EventHandler(this.OnBack);
		this.btnNextTNVED2.Clicked += new global::System.EventHandler(this.OnSave);
	}
}
