
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook stackPages;

	private global::Gtk.VBox vboxPageTNVED;

	private global::Gtk.HBox hbox17;

	private global::Gtk.Alignment alignment1;

	private global::Gtk.Label label5;

	private global::Gtk.FileChooserButton filechooserTNVED;

	private global::Gtk.Frame frameTNVED;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hboxTNVEDname;

	private global::Gtk.Label labelTNVEDname;

	private global::Gtk.ComboBox combTNVEDname;

	private global::Gtk.HBox hboxTNVEDname2;

	private global::Gtk.Label labelTNVEDname2;

	private global::Gtk.ComboBox combTNVEDcode;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button btnNextTNVED;

	private global::Gtk.Label label7;

	private global::Gtk.VBox vboxPageParty;

	private global::Gtk.HBox hbox18;

	private global::Gtk.Alignment alignment2;

	private global::Gtk.Label label6;

	private global::Gtk.FileChooserButton filechooserParty;

	private global::Gtk.Frame framePartyList1;

	private global::Gtk.Alignment frame;

	private global::Gtk.VBox vbox9;

	private global::Gtk.HBox hboxTNVEDname1;

	private global::Gtk.Label labelTNVEDname1;

	private global::Gtk.ComboBox combPartyName;

	private global::Gtk.HBox hboxTNVEDname4;

	private global::Gtk.Label labelTNVEDname4;

	private global::Gtk.ComboBox combPartyNum;

	private global::Gtk.HBox hboxTNVEDname3;

	private global::Gtk.Label labelTNVEDname3;

	private global::Gtk.ComboBox combPartyAllCount;

	private global::Gtk.HBox hboxTNVEDname6;

	private global::Gtk.Label labelTNVEDname6;

	private global::Gtk.ComboBox combPartyCountByType;

	private global::Gtk.HBox hboxTNVEDname5;

	private global::Gtk.Label labelTNVEDname5;

	private global::Gtk.ComboBox combPartyCost;

	private global::Gtk.Frame framePartyList2;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hboxTNVEDname8;

	private global::Gtk.Label labelTNVEDname8;

	private global::Gtk.ComboBox combBagOrderNumber;

	private global::Gtk.HBox hboxTNVEDname7;

	private global::Gtk.Label labelTNVEDname7;

	private global::Gtk.ComboBox combBagNumber;

	private global::Gtk.HBox hboxTNVEDname9;

	private global::Gtk.Label labelTNVEDname9;

	private global::Gtk.ComboBox combWeight;

	private global::Gtk.Frame framePartyList3;

	private global::Gtk.Alignment GtkAlignment3;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hboxTNVEDname18;

	private global::Gtk.Label labelTNVEDname16;

	private global::Gtk.Entry entrySumGross;

	private global::Gtk.HBox hboxTNVEDname19;

	private global::Gtk.Label labelTNVEDname17;

	private global::Gtk.Entry entrySumNetWeight;

	private global::Gtk.HBox hboxTNVEDname20;

	private global::Gtk.Label labelTNVEDname18;

	private global::Gtk.Entry entrySumPackageWeight;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button btnNextParty;

	private global::Gtk.Button button5;

	private global::Gtk.Label label8;

	private global::Gtk.VBox vboxPageTNVED2;

	private global::Gtk.HBox hbox20;

	private global::Gtk.Alignment alignment4;

	private global::Gtk.Label label10;

	private global::Gtk.FileChooserButton filechooserTransport;

	private global::Gtk.Frame frameTransport;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.VBox vboxTransport;

	private global::Gtk.HBox hboxTNVEDname10;

	private global::Gtk.Label labelDriver;

	private global::Gtk.ComboBox combDriver;

	private global::Gtk.HBox hboxTNVEDname11;

	private global::Gtk.Label labelCar;

	private global::Gtk.ComboBox combCar;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Button btnNextTransport;

	private global::Gtk.Button button7;

	private global::Gtk.Label label11;

	private global::Gtk.VBox vboxPageTemplates;

	private global::Gtk.HBox hboxPackageTemplate;

	private global::Gtk.Alignment alignment5;

	private global::Gtk.Label label12;

	private global::Gtk.FileChooserButton filechooserTemplatePackingList;

	private global::Gtk.HBox hboxSpecificationTemplate;

	private global::Gtk.Alignment alignment6;

	private global::Gtk.Label label13;

	private global::Gtk.FileChooserButton filechooserTemplateSpecification;

	private global::Gtk.HBox hboxCPMTemplate;

	private global::Gtk.Alignment alignment7;

	private global::Gtk.Label label14;

	private global::Gtk.FileChooserButton filechooserTemplateCPM;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.HBox hboxCPMTemplate3;

	private global::Gtk.Alignment alignment10;

	private global::Gtk.Label label17;

	private global::Gtk.FileChooserButton filechooserIgnoreCodes;

	private global::Gtk.HBox hboxCPMTemplate2;

	private global::Gtk.Alignment alignment9;

	private global::Gtk.Label label16;

	private global::Gtk.Entry entrySenderCity;

	private global::Gtk.HBox hboxCPMTemplate1;

	private global::Gtk.Alignment alignment8;

	private global::Gtk.Label label15;

	private global::Gtk.Entry entryPartyNumber;

	private global::Gtk.Label label9;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Button btnGenerate;

	private global::Gtk.Button button6;

	private global::Gtk.Label label1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Товары");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.stackPages = new global::Gtk.Notebook();
		this.stackPages.Name = "stackPages";
		this.stackPages.CurrentPage = 0;
		this.stackPages.ShowBorder = false;
		// Container child stackPages.Gtk.Notebook+NotebookChild
		this.vboxPageTNVED = new global::Gtk.VBox();
		this.vboxPageTNVED.Name = "vboxPageTNVED";
		this.vboxPageTNVED.Spacing = 6;
		this.vboxPageTNVED.BorderWidth = ((uint)(4));
		// Container child vboxPageTNVED.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.alignment1.LeftPadding = ((uint)(4));
		// Container child alignment1.Gtk.Container+ContainerChild
		this.label5 = new global::Gtk.Label();
		this.label5.WidthRequest = 200;
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Файл \"Коды ТН ВЭД\":");
		this.alignment1.Add(this.label5);
		this.hbox17.Add(this.alignment1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.alignment1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.filechooserTNVED = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Коды ТН ВЭД\n"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserTNVED.Name = "filechooserTNVED";
		this.hbox17.Add(this.filechooserTNVED);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.filechooserTNVED]));
		w3.Position = 1;
		this.vboxPageTNVED.Add(this.hbox17);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED[this.hbox17]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vboxPageTNVED.Gtk.Box+BoxChild
		this.frameTNVED = new global::Gtk.Frame();
		this.frameTNVED.Sensitive = false;
		this.frameTNVED.Name = "frameTNVED";
		// Container child frameTNVED.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.BorderWidth = ((uint)(2));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hboxTNVEDname = new global::Gtk.HBox();
		this.hboxTNVEDname.Name = "hboxTNVEDname";
		this.hboxTNVEDname.Spacing = 6;
		// Container child hboxTNVEDname.Gtk.Box+BoxChild
		this.labelTNVEDname = new global::Gtk.Label();
		this.labelTNVEDname.WidthRequest = 200;
		this.labelTNVEDname.Name = "labelTNVEDname";
		this.labelTNVEDname.Xalign = 0F;
		this.labelTNVEDname.LabelProp = global::Mono.Unix.Catalog.GetString("Наименование отправления:");
		this.hboxTNVEDname.Add(this.labelTNVEDname);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname[this.labelTNVEDname]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hboxTNVEDname.Gtk.Box+BoxChild
		this.combTNVEDname = global::Gtk.ComboBox.NewText();
		this.combTNVEDname.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combTNVEDname.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combTNVEDname.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combTNVEDname.Name = "combTNVEDname";
		this.combTNVEDname.Active = 0;
		this.hboxTNVEDname.Add(this.combTNVEDname);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname[this.combTNVEDname]));
		w6.Position = 1;
		this.vbox1.Add(this.hboxTNVEDname);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxTNVEDname]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hboxTNVEDname2 = new global::Gtk.HBox();
		this.hboxTNVEDname2.Name = "hboxTNVEDname2";
		this.hboxTNVEDname2.Spacing = 6;
		// Container child hboxTNVEDname2.Gtk.Box+BoxChild
		this.labelTNVEDname2 = new global::Gtk.Label();
		this.labelTNVEDname2.WidthRequest = 200;
		this.labelTNVEDname2.Name = "labelTNVEDname2";
		this.labelTNVEDname2.Xalign = 0F;
		this.labelTNVEDname2.LabelProp = global::Mono.Unix.Catalog.GetString("Код ТНВЭД:");
		this.hboxTNVEDname2.Add(this.labelTNVEDname2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname2[this.labelTNVEDname2]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hboxTNVEDname2.Gtk.Box+BoxChild
		this.combTNVEDcode = global::Gtk.ComboBox.NewText();
		this.combTNVEDcode.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combTNVEDcode.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combTNVEDcode.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combTNVEDcode.Name = "combTNVEDcode";
		this.combTNVEDcode.Active = 1;
		this.hboxTNVEDname2.Add(this.combTNVEDcode);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname2[this.combTNVEDcode]));
		w9.Position = 1;
		this.vbox1.Add(this.hboxTNVEDname2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxTNVEDname2]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.GtkAlignment.Add(this.vbox1);
		this.frameTNVED.Add(this.GtkAlignment);
		this.vboxPageTNVED.Add(this.frameTNVED);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED[this.frameTNVED]));
		w13.Position = 1;
		// Container child vboxPageTNVED.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnNextTNVED = new global::Gtk.Button();
		this.btnNextTNVED.WidthRequest = 80;
		this.btnNextTNVED.CanFocus = true;
		this.btnNextTNVED.Name = "btnNextTNVED";
		this.btnNextTNVED.UseUnderline = true;
		this.btnNextTNVED.Label = global::Mono.Unix.Catalog.GetString("Далее");
		this.hbox3.Add(this.btnNextTNVED);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnNextTNVED]));
		w14.PackType = ((global::Gtk.PackType)(1));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		this.vboxPageTNVED.Add(this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED[this.hbox3]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.stackPages.Add(this.vboxPageTNVED);
		// Notebook tab
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Коды ТН ВЭД");
		this.stackPages.SetTabLabel(this.vboxPageTNVED, this.label7);
		this.label7.ShowAll();
		// Container child stackPages.Gtk.Notebook+NotebookChild
		this.vboxPageParty = new global::Gtk.VBox();
		this.vboxPageParty.Name = "vboxPageParty";
		this.vboxPageParty.Spacing = 6;
		this.vboxPageParty.BorderWidth = ((uint)(4));
		// Container child vboxPageParty.Gtk.Box+BoxChild
		this.hbox18 = new global::Gtk.HBox();
		this.hbox18.Name = "hbox18";
		this.hbox18.Spacing = 6;
		// Container child hbox18.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.alignment2.LeftPadding = ((uint)(4));
		// Container child alignment2.Gtk.Container+ContainerChild
		this.label6 = new global::Gtk.Label();
		this.label6.WidthRequest = 200;
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Файл \"Партия\":");
		this.alignment2.Add(this.label6);
		this.hbox18.Add(this.alignment2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.alignment2]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox18.Gtk.Box+BoxChild
		this.filechooserParty = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Файл \"Партия\""), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserParty.Name = "filechooserParty";
		this.hbox18.Add(this.filechooserParty);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.filechooserParty]));
		w19.Position = 1;
		this.vboxPageParty.Add(this.hbox18);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vboxPageParty[this.hbox18]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vboxPageParty.Gtk.Box+BoxChild
		this.framePartyList1 = new global::Gtk.Frame();
		this.framePartyList1.Sensitive = false;
		this.framePartyList1.Name = "framePartyList1";
		// Container child framePartyList1.Gtk.Container+ContainerChild
		this.frame = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.frame.Name = "frame";
		this.frame.BorderWidth = ((uint)(2));
		// Container child frame.Gtk.Container+ContainerChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hboxTNVEDname1 = new global::Gtk.HBox();
		this.hboxTNVEDname1.Name = "hboxTNVEDname1";
		this.hboxTNVEDname1.Spacing = 6;
		// Container child hboxTNVEDname1.Gtk.Box+BoxChild
		this.labelTNVEDname1 = new global::Gtk.Label();
		this.labelTNVEDname1.WidthRequest = 200;
		this.labelTNVEDname1.Name = "labelTNVEDname1";
		this.labelTNVEDname1.Xalign = 0F;
		this.labelTNVEDname1.LabelProp = global::Mono.Unix.Catalog.GetString("Наименование товара:");
		this.hboxTNVEDname1.Add(this.labelTNVEDname1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname1[this.labelTNVEDname1]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hboxTNVEDname1.Gtk.Box+BoxChild
		this.combPartyName = global::Gtk.ComboBox.NewText();
		this.combPartyName.AppendText(global::Mono.Unix.Catalog.GetString("AK"));
		this.combPartyName.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combPartyName.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combPartyName.AppendText("");
		this.combPartyName.Name = "combPartyName";
		this.combPartyName.Active = 0;
		this.hboxTNVEDname1.Add(this.combPartyName);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname1[this.combPartyName]));
		w22.Position = 1;
		this.vbox9.Add(this.hboxTNVEDname1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hboxTNVEDname1]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hboxTNVEDname4 = new global::Gtk.HBox();
		this.hboxTNVEDname4.Name = "hboxTNVEDname4";
		this.hboxTNVEDname4.Spacing = 6;
		// Container child hboxTNVEDname4.Gtk.Box+BoxChild
		this.labelTNVEDname4 = new global::Gtk.Label();
		this.labelTNVEDname4.WidthRequest = 200;
		this.labelTNVEDname4.Name = "labelTNVEDname4";
		this.labelTNVEDname4.Xalign = 0F;
		this.labelTNVEDname4.LabelProp = global::Mono.Unix.Catalog.GetString("Номер отправления:");
		this.hboxTNVEDname4.Add(this.labelTNVEDname4);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname4[this.labelTNVEDname4]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hboxTNVEDname4.Gtk.Box+BoxChild
		this.combPartyNum = global::Gtk.ComboBox.NewText();
		this.combPartyNum.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combPartyNum.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combPartyNum.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combPartyNum.AppendText("");
		this.combPartyNum.Name = "combPartyNum";
		this.combPartyNum.Active = 0;
		this.hboxTNVEDname4.Add(this.combPartyNum);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname4[this.combPartyNum]));
		w25.Position = 1;
		this.vbox9.Add(this.hboxTNVEDname4);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hboxTNVEDname4]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hboxTNVEDname3 = new global::Gtk.HBox();
		this.hboxTNVEDname3.Name = "hboxTNVEDname3";
		this.hboxTNVEDname3.Spacing = 6;
		// Container child hboxTNVEDname3.Gtk.Box+BoxChild
		this.labelTNVEDname3 = new global::Gtk.Label();
		this.labelTNVEDname3.WidthRequest = 200;
		this.labelTNVEDname3.Name = "labelTNVEDname3";
		this.labelTNVEDname3.Xalign = 0F;
		this.labelTNVEDname3.LabelProp = global::Mono.Unix.Catalog.GetString("Суммарное количество вложений:");
		this.hboxTNVEDname3.Add(this.labelTNVEDname3);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname3[this.labelTNVEDname3]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hboxTNVEDname3.Gtk.Box+BoxChild
		this.combPartyAllCount = global::Gtk.ComboBox.NewText();
		this.combPartyAllCount.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.combPartyAllCount.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combPartyAllCount.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combPartyAllCount.Name = "combPartyAllCount";
		this.combPartyAllCount.Active = 0;
		this.hboxTNVEDname3.Add(this.combPartyAllCount);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname3[this.combPartyAllCount]));
		w28.Position = 1;
		this.vbox9.Add(this.hboxTNVEDname3);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hboxTNVEDname3]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hboxTNVEDname6 = new global::Gtk.HBox();
		this.hboxTNVEDname6.Name = "hboxTNVEDname6";
		this.hboxTNVEDname6.Spacing = 6;
		// Container child hboxTNVEDname6.Gtk.Box+BoxChild
		this.labelTNVEDname6 = new global::Gtk.Label();
		this.labelTNVEDname6.WidthRequest = 200;
		this.labelTNVEDname6.Name = "labelTNVEDname6";
		this.labelTNVEDname6.Xalign = 0F;
		this.labelTNVEDname6.LabelProp = global::Mono.Unix.Catalog.GetString("Количество объектов в посылке:");
		this.hboxTNVEDname6.Add(this.labelTNVEDname6);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname6[this.labelTNVEDname6]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hboxTNVEDname6.Gtk.Box+BoxChild
		this.combPartyCountByType = global::Gtk.ComboBox.NewText();
		this.combPartyCountByType.AppendText(global::Mono.Unix.Catalog.GetString("AG"));
		this.combPartyCountByType.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combPartyCountByType.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combPartyCountByType.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.combPartyCountByType.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.combPartyCountByType.AppendText("");
		this.combPartyCountByType.Name = "combPartyCountByType";
		this.combPartyCountByType.Active = 0;
		this.hboxTNVEDname6.Add(this.combPartyCountByType);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname6[this.combPartyCountByType]));
		w31.Position = 1;
		this.vbox9.Add(this.hboxTNVEDname6);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hboxTNVEDname6]));
		w32.Position = 3;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hboxTNVEDname5 = new global::Gtk.HBox();
		this.hboxTNVEDname5.Name = "hboxTNVEDname5";
		this.hboxTNVEDname5.Spacing = 6;
		// Container child hboxTNVEDname5.Gtk.Box+BoxChild
		this.labelTNVEDname5 = new global::Gtk.Label();
		this.labelTNVEDname5.WidthRequest = 200;
		this.labelTNVEDname5.Name = "labelTNVEDname5";
		this.labelTNVEDname5.Xalign = 0F;
		this.labelTNVEDname5.LabelProp = global::Mono.Unix.Catalog.GetString("Цена:");
		this.hboxTNVEDname5.Add(this.labelTNVEDname5);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname5[this.labelTNVEDname5]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hboxTNVEDname5.Gtk.Box+BoxChild
		this.combPartyCost = global::Gtk.ComboBox.NewText();
		this.combPartyCost.AppendText(global::Mono.Unix.Catalog.GetString("AO"));
		this.combPartyCost.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combPartyCost.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combPartyCost.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.combPartyCost.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.combPartyCost.AppendText("");
		this.combPartyCost.Name = "combPartyCost";
		this.combPartyCost.Active = 0;
		this.hboxTNVEDname5.Add(this.combPartyCost);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname5[this.combPartyCost]));
		w34.Position = 1;
		this.vbox9.Add(this.hboxTNVEDname5);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hboxTNVEDname5]));
		w35.Position = 4;
		w35.Expand = false;
		w35.Fill = false;
		this.frame.Add(this.vbox9);
		this.framePartyList1.Add(this.frame);
		this.vboxPageParty.Add(this.framePartyList1);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vboxPageParty[this.framePartyList1]));
		w38.Position = 1;
		// Container child vboxPageParty.Gtk.Box+BoxChild
		this.framePartyList2 = new global::Gtk.Frame();
		this.framePartyList2.Sensitive = false;
		this.framePartyList2.Name = "framePartyList2";
		// Container child framePartyList2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.BorderWidth = ((uint)(2));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hboxTNVEDname8 = new global::Gtk.HBox();
		this.hboxTNVEDname8.Name = "hboxTNVEDname8";
		this.hboxTNVEDname8.Spacing = 6;
		// Container child hboxTNVEDname8.Gtk.Box+BoxChild
		this.labelTNVEDname8 = new global::Gtk.Label();
		this.labelTNVEDname8.WidthRequest = 200;
		this.labelTNVEDname8.Name = "labelTNVEDname8";
		this.labelTNVEDname8.Xalign = 0F;
		this.labelTNVEDname8.LabelProp = global::Mono.Unix.Catalog.GetString("Номер отправления:");
		this.hboxTNVEDname8.Add(this.labelTNVEDname8);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname8[this.labelTNVEDname8]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child hboxTNVEDname8.Gtk.Box+BoxChild
		this.combBagOrderNumber = global::Gtk.ComboBox.NewText();
		this.combBagOrderNumber.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combBagOrderNumber.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combBagOrderNumber.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combBagOrderNumber.Name = "combBagOrderNumber";
		this.combBagOrderNumber.Active = 0;
		this.hboxTNVEDname8.Add(this.combBagOrderNumber);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname8[this.combBagOrderNumber]));
		w40.Position = 1;
		this.vbox2.Add(this.hboxTNVEDname8);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxTNVEDname8]));
		w41.Position = 0;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hboxTNVEDname7 = new global::Gtk.HBox();
		this.hboxTNVEDname7.Name = "hboxTNVEDname7";
		this.hboxTNVEDname7.Spacing = 6;
		// Container child hboxTNVEDname7.Gtk.Box+BoxChild
		this.labelTNVEDname7 = new global::Gtk.Label();
		this.labelTNVEDname7.WidthRequest = 200;
		this.labelTNVEDname7.Name = "labelTNVEDname7";
		this.labelTNVEDname7.Xalign = 0F;
		this.labelTNVEDname7.LabelProp = global::Mono.Unix.Catalog.GetString("Номер мешка:");
		this.hboxTNVEDname7.Add(this.labelTNVEDname7);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname7[this.labelTNVEDname7]));
		w42.Position = 0;
		w42.Expand = false;
		w42.Fill = false;
		// Container child hboxTNVEDname7.Gtk.Box+BoxChild
		this.combBagNumber = global::Gtk.ComboBox.NewText();
		this.combBagNumber.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combBagNumber.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combBagNumber.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combBagNumber.Name = "combBagNumber";
		this.combBagNumber.Active = 0;
		this.hboxTNVEDname7.Add(this.combBagNumber);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname7[this.combBagNumber]));
		w43.Position = 1;
		this.vbox2.Add(this.hboxTNVEDname7);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxTNVEDname7]));
		w44.Position = 1;
		w44.Expand = false;
		w44.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hboxTNVEDname9 = new global::Gtk.HBox();
		this.hboxTNVEDname9.Name = "hboxTNVEDname9";
		this.hboxTNVEDname9.Spacing = 6;
		// Container child hboxTNVEDname9.Gtk.Box+BoxChild
		this.labelTNVEDname9 = new global::Gtk.Label();
		this.labelTNVEDname9.WidthRequest = 200;
		this.labelTNVEDname9.Name = "labelTNVEDname9";
		this.labelTNVEDname9.Xalign = 0F;
		this.labelTNVEDname9.LabelProp = global::Mono.Unix.Catalog.GetString("Вес:");
		this.hboxTNVEDname9.Add(this.labelTNVEDname9);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname9[this.labelTNVEDname9]));
		w45.Position = 0;
		w45.Expand = false;
		w45.Fill = false;
		// Container child hboxTNVEDname9.Gtk.Box+BoxChild
		this.combWeight = global::Gtk.ComboBox.NewText();
		this.combWeight.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combWeight.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combWeight.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combWeight.Name = "combWeight";
		this.combWeight.Active = 0;
		this.hboxTNVEDname9.Add(this.combWeight);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname9[this.combWeight]));
		w46.Position = 1;
		this.vbox2.Add(this.hboxTNVEDname9);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxTNVEDname9]));
		w47.Position = 2;
		w47.Expand = false;
		w47.Fill = false;
		this.GtkAlignment1.Add(this.vbox2);
		this.framePartyList2.Add(this.GtkAlignment1);
		this.vboxPageParty.Add(this.framePartyList2);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vboxPageParty[this.framePartyList2]));
		w50.Position = 2;
		w50.Expand = false;
		w50.Fill = false;
		// Container child vboxPageParty.Gtk.Box+BoxChild
		this.framePartyList3 = new global::Gtk.Frame();
		this.framePartyList3.Sensitive = false;
		this.framePartyList3.Name = "framePartyList3";
		// Container child framePartyList3.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.BorderWidth = ((uint)(2));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hboxTNVEDname18 = new global::Gtk.HBox();
		this.hboxTNVEDname18.Name = "hboxTNVEDname18";
		this.hboxTNVEDname18.Spacing = 6;
		// Container child hboxTNVEDname18.Gtk.Box+BoxChild
		this.labelTNVEDname16 = new global::Gtk.Label();
		this.labelTNVEDname16.WidthRequest = 200;
		this.labelTNVEDname16.Name = "labelTNVEDname16";
		this.labelTNVEDname16.Xalign = 0F;
		this.labelTNVEDname16.LabelProp = global::Mono.Unix.Catalog.GetString("Общий вес брутто:");
		this.hboxTNVEDname18.Add(this.labelTNVEDname16);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname18[this.labelTNVEDname16]));
		w51.Position = 0;
		w51.Expand = false;
		w51.Fill = false;
		// Container child hboxTNVEDname18.Gtk.Box+BoxChild
		this.entrySumGross = new global::Gtk.Entry();
		this.entrySumGross.CanFocus = true;
		this.entrySumGross.Name = "entrySumGross";
		this.entrySumGross.Text = global::Mono.Unix.Catalog.GetString("E3");
		this.entrySumGross.IsEditable = true;
		this.entrySumGross.InvisibleChar = '●';
		this.hboxTNVEDname18.Add(this.entrySumGross);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname18[this.entrySumGross]));
		w52.Position = 1;
		this.vbox3.Add(this.hboxTNVEDname18);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hboxTNVEDname18]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hboxTNVEDname19 = new global::Gtk.HBox();
		this.hboxTNVEDname19.Name = "hboxTNVEDname19";
		this.hboxTNVEDname19.Spacing = 6;
		// Container child hboxTNVEDname19.Gtk.Box+BoxChild
		this.labelTNVEDname17 = new global::Gtk.Label();
		this.labelTNVEDname17.WidthRequest = 200;
		this.labelTNVEDname17.Name = "labelTNVEDname17";
		this.labelTNVEDname17.Xalign = 0F;
		this.labelTNVEDname17.LabelProp = global::Mono.Unix.Catalog.GetString("Общий вес нетто:");
		this.hboxTNVEDname19.Add(this.labelTNVEDname17);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname19[this.labelTNVEDname17]));
		w54.Position = 0;
		w54.Expand = false;
		w54.Fill = false;
		// Container child hboxTNVEDname19.Gtk.Box+BoxChild
		this.entrySumNetWeight = new global::Gtk.Entry();
		this.entrySumNetWeight.CanFocus = true;
		this.entrySumNetWeight.Name = "entrySumNetWeight";
		this.entrySumNetWeight.Text = global::Mono.Unix.Catalog.GetString("E1");
		this.entrySumNetWeight.IsEditable = true;
		this.entrySumNetWeight.InvisibleChar = '●';
		this.hboxTNVEDname19.Add(this.entrySumNetWeight);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname19[this.entrySumNetWeight]));
		w55.Position = 1;
		this.vbox3.Add(this.hboxTNVEDname19);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hboxTNVEDname19]));
		w56.Position = 1;
		w56.Expand = false;
		w56.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hboxTNVEDname20 = new global::Gtk.HBox();
		this.hboxTNVEDname20.Name = "hboxTNVEDname20";
		this.hboxTNVEDname20.Spacing = 6;
		// Container child hboxTNVEDname20.Gtk.Box+BoxChild
		this.labelTNVEDname18 = new global::Gtk.Label();
		this.labelTNVEDname18.WidthRequest = 200;
		this.labelTNVEDname18.Name = "labelTNVEDname18";
		this.labelTNVEDname18.Xalign = 0F;
		this.labelTNVEDname18.LabelProp = global::Mono.Unix.Catalog.GetString("Общий вес упаковки:");
		this.hboxTNVEDname20.Add(this.labelTNVEDname18);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname20[this.labelTNVEDname18]));
		w57.Position = 0;
		w57.Expand = false;
		w57.Fill = false;
		// Container child hboxTNVEDname20.Gtk.Box+BoxChild
		this.entrySumPackageWeight = new global::Gtk.Entry();
		this.entrySumPackageWeight.CanFocus = true;
		this.entrySumPackageWeight.Name = "entrySumPackageWeight";
		this.entrySumPackageWeight.Text = global::Mono.Unix.Catalog.GetString("E2");
		this.entrySumPackageWeight.IsEditable = true;
		this.entrySumPackageWeight.InvisibleChar = '●';
		this.hboxTNVEDname20.Add(this.entrySumPackageWeight);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname20[this.entrySumPackageWeight]));
		w58.Position = 1;
		this.vbox3.Add(this.hboxTNVEDname20);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hboxTNVEDname20]));
		w59.Position = 2;
		w59.Expand = false;
		w59.Fill = false;
		this.GtkAlignment3.Add(this.vbox3);
		this.framePartyList3.Add(this.GtkAlignment3);
		this.vboxPageParty.Add(this.framePartyList3);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vboxPageParty[this.framePartyList3]));
		w62.Position = 3;
		// Container child vboxPageParty.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnNextParty = new global::Gtk.Button();
		this.btnNextParty.WidthRequest = 80;
		this.btnNextParty.CanFocus = true;
		this.btnNextParty.Name = "btnNextParty";
		this.btnNextParty.UseUnderline = true;
		this.btnNextParty.Label = global::Mono.Unix.Catalog.GetString("Далее");
		this.hbox4.Add(this.btnNextParty);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnNextParty]));
		w63.PackType = ((global::Gtk.PackType)(1));
		w63.Position = 0;
		w63.Expand = false;
		w63.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.WidthRequest = 80;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Назад");
		this.hbox4.Add(this.button5);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button5]));
		w64.PackType = ((global::Gtk.PackType)(1));
		w64.Position = 1;
		w64.Expand = false;
		w64.Fill = false;
		this.vboxPageParty.Add(this.hbox4);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vboxPageParty[this.hbox4]));
		w65.Position = 4;
		w65.Expand = false;
		w65.Fill = false;
		this.stackPages.Add(this.vboxPageParty);
		global::Gtk.Notebook.NotebookChild w66 = ((global::Gtk.Notebook.NotebookChild)(this.stackPages[this.vboxPageParty]));
		w66.Position = 1;
		// Notebook tab
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Партия");
		this.stackPages.SetTabLabel(this.vboxPageParty, this.label8);
		this.label8.ShowAll();
		// Container child stackPages.Gtk.Notebook+NotebookChild
		this.vboxPageTNVED2 = new global::Gtk.VBox();
		this.vboxPageTNVED2.Name = "vboxPageTNVED2";
		this.vboxPageTNVED2.Spacing = 6;
		this.vboxPageTNVED2.BorderWidth = ((uint)(4));
		// Container child vboxPageTNVED2.Gtk.Box+BoxChild
		this.hbox20 = new global::Gtk.HBox();
		this.hbox20.Name = "hbox20";
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment4.Name = "alignment4";
		this.alignment4.LeftPadding = ((uint)(4));
		// Container child alignment4.Gtk.Container+ContainerChild
		this.label10 = new global::Gtk.Label();
		this.label10.WidthRequest = 200;
		this.label10.Name = "label10";
		this.label10.Xalign = 0F;
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Файл \"Транспорт\":");
		this.alignment4.Add(this.label10);
		this.hbox20.Add(this.alignment4);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.alignment4]));
		w68.Position = 0;
		w68.Expand = false;
		w68.Fill = false;
		// Container child hbox20.Gtk.Box+BoxChild
		this.filechooserTransport = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Файл \"Транспорт\""), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserTransport.Name = "filechooserTransport";
		this.hbox20.Add(this.filechooserTransport);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.filechooserTransport]));
		w69.Position = 1;
		this.vboxPageTNVED2.Add(this.hbox20);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED2[this.hbox20]));
		w70.Position = 0;
		w70.Expand = false;
		w70.Fill = false;
		// Container child vboxPageTNVED2.Gtk.Box+BoxChild
		this.frameTransport = new global::Gtk.Frame();
		this.frameTransport.Sensitive = false;
		this.frameTransport.Name = "frameTransport";
		// Container child frameTransport.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.BorderWidth = ((uint)(2));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vboxTransport = new global::Gtk.VBox();
		this.vboxTransport.Name = "vboxTransport";
		this.vboxTransport.Spacing = 6;
		// Container child vboxTransport.Gtk.Box+BoxChild
		this.hboxTNVEDname10 = new global::Gtk.HBox();
		this.hboxTNVEDname10.Name = "hboxTNVEDname10";
		this.hboxTNVEDname10.Spacing = 6;
		// Container child hboxTNVEDname10.Gtk.Box+BoxChild
		this.labelDriver = new global::Gtk.Label();
		this.labelDriver.WidthRequest = 200;
		this.labelDriver.Name = "labelDriver";
		this.labelDriver.Xalign = 0F;
		this.labelDriver.LabelProp = global::Mono.Unix.Catalog.GetString("Водитель:");
		this.hboxTNVEDname10.Add(this.labelDriver);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname10[this.labelDriver]));
		w71.Position = 0;
		w71.Expand = false;
		w71.Fill = false;
		// Container child hboxTNVEDname10.Gtk.Box+BoxChild
		this.combDriver = global::Gtk.ComboBox.NewText();
		this.combDriver.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combDriver.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combDriver.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combDriver.Name = "combDriver";
		this.combDriver.Active = 0;
		this.hboxTNVEDname10.Add(this.combDriver);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname10[this.combDriver]));
		w72.Position = 1;
		this.vboxTransport.Add(this.hboxTNVEDname10);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vboxTransport[this.hboxTNVEDname10]));
		w73.Position = 0;
		w73.Expand = false;
		w73.Fill = false;
		// Container child vboxTransport.Gtk.Box+BoxChild
		this.hboxTNVEDname11 = new global::Gtk.HBox();
		this.hboxTNVEDname11.Name = "hboxTNVEDname11";
		this.hboxTNVEDname11.Spacing = 6;
		// Container child hboxTNVEDname11.Gtk.Box+BoxChild
		this.labelCar = new global::Gtk.Label();
		this.labelCar.WidthRequest = 200;
		this.labelCar.Name = "labelCar";
		this.labelCar.Xalign = 0F;
		this.labelCar.LabelProp = global::Mono.Unix.Catalog.GetString("Автомобиль:");
		this.hboxTNVEDname11.Add(this.labelCar);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname11[this.labelCar]));
		w74.Position = 0;
		w74.Expand = false;
		w74.Fill = false;
		// Container child hboxTNVEDname11.Gtk.Box+BoxChild
		this.combCar = global::Gtk.ComboBox.NewText();
		this.combCar.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.combCar.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.combCar.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.combCar.Name = "combCar";
		this.combCar.Active = 1;
		this.hboxTNVEDname11.Add(this.combCar);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hboxTNVEDname11[this.combCar]));
		w75.Position = 1;
		this.vboxTransport.Add(this.hboxTNVEDname11);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vboxTransport[this.hboxTNVEDname11]));
		w76.Position = 1;
		w76.Expand = false;
		w76.Fill = false;
		this.GtkAlignment2.Add(this.vboxTransport);
		this.frameTransport.Add(this.GtkAlignment2);
		this.vboxPageTNVED2.Add(this.frameTransport);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED2[this.frameTransport]));
		w79.Position = 1;
		// Container child vboxPageTNVED2.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.btnNextTransport = new global::Gtk.Button();
		this.btnNextTransport.WidthRequest = 80;
		this.btnNextTransport.CanFocus = true;
		this.btnNextTransport.Name = "btnNextTransport";
		this.btnNextTransport.UseUnderline = true;
		this.btnNextTransport.Label = global::Mono.Unix.Catalog.GetString("Далее");
		this.hbox13.Add(this.btnNextTransport);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.btnNextTransport]));
		w80.PackType = ((global::Gtk.PackType)(1));
		w80.Position = 0;
		w80.Expand = false;
		w80.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.WidthRequest = 80;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Назад");
		this.hbox13.Add(this.button7);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button7]));
		w81.PackType = ((global::Gtk.PackType)(1));
		w81.Position = 1;
		w81.Expand = false;
		w81.Fill = false;
		this.vboxPageTNVED2.Add(this.hbox13);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vboxPageTNVED2[this.hbox13]));
		w82.Position = 2;
		w82.Expand = false;
		w82.Fill = false;
		this.stackPages.Add(this.vboxPageTNVED2);
		global::Gtk.Notebook.NotebookChild w83 = ((global::Gtk.Notebook.NotebookChild)(this.stackPages[this.vboxPageTNVED2]));
		w83.Position = 2;
		// Notebook tab
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Транспорт");
		this.stackPages.SetTabLabel(this.vboxPageTNVED2, this.label11);
		this.label11.ShowAll();
		// Container child stackPages.Gtk.Notebook+NotebookChild
		this.vboxPageTemplates = new global::Gtk.VBox();
		this.vboxPageTemplates.Name = "vboxPageTemplates";
		this.vboxPageTemplates.Spacing = 6;
		this.vboxPageTemplates.BorderWidth = ((uint)(4));
		// Container child vboxPageTemplates.Gtk.Box+BoxChild
		this.hboxPackageTemplate = new global::Gtk.HBox();
		this.hboxPackageTemplate.Name = "hboxPackageTemplate";
		this.hboxPackageTemplate.Spacing = 6;
		// Container child hboxPackageTemplate.Gtk.Box+BoxChild
		this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment5.Name = "alignment5";
		this.alignment5.LeftPadding = ((uint)(4));
		// Container child alignment5.Gtk.Container+ContainerChild
		this.label12 = new global::Gtk.Label();
		this.label12.WidthRequest = 200;
		this.label12.Name = "label12";
		this.label12.Xalign = 0F;
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Шаблон \"Упаковочный лист\":");
		this.alignment5.Add(this.label12);
		this.hboxPackageTemplate.Add(this.alignment5);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hboxPackageTemplate[this.alignment5]));
		w85.Position = 0;
		w85.Expand = false;
		w85.Fill = false;
		// Container child hboxPackageTemplate.Gtk.Box+BoxChild
		this.filechooserTemplatePackingList = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Шаблон \"Упаковочный лист\""), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserTemplatePackingList.Name = "filechooserTemplatePackingList";
		this.hboxPackageTemplate.Add(this.filechooserTemplatePackingList);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hboxPackageTemplate[this.filechooserTemplatePackingList]));
		w86.Position = 1;
		this.vboxPageTemplates.Add(this.hboxPackageTemplate);
		global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vboxPageTemplates[this.hboxPackageTemplate]));
		w87.Position = 0;
		w87.Expand = false;
		w87.Fill = false;
		// Container child vboxPageTemplates.Gtk.Box+BoxChild
		this.hboxSpecificationTemplate = new global::Gtk.HBox();
		this.hboxSpecificationTemplate.Name = "hboxSpecificationTemplate";
		this.hboxSpecificationTemplate.Spacing = 6;
		// Container child hboxSpecificationTemplate.Gtk.Box+BoxChild
		this.alignment6 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment6.Name = "alignment6";
		this.alignment6.LeftPadding = ((uint)(4));
		// Container child alignment6.Gtk.Container+ContainerChild
		this.label13 = new global::Gtk.Label();
		this.label13.WidthRequest = 200;
		this.label13.Name = "label13";
		this.label13.Xalign = 0F;
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Шаблон \"Спецификация\":");
		this.alignment6.Add(this.label13);
		this.hboxSpecificationTemplate.Add(this.alignment6);
		global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hboxSpecificationTemplate[this.alignment6]));
		w89.Position = 0;
		w89.Expand = false;
		w89.Fill = false;
		// Container child hboxSpecificationTemplate.Gtk.Box+BoxChild
		this.filechooserTemplateSpecification = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Шаблон \"Спецификация\""), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserTemplateSpecification.Name = "filechooserTemplateSpecification";
		this.hboxSpecificationTemplate.Add(this.filechooserTemplateSpecification);
		global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.hboxSpecificationTemplate[this.filechooserTemplateSpecification]));
		w90.Position = 1;
		this.vboxPageTemplates.Add(this.hboxSpecificationTemplate);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vboxPageTemplates[this.hboxSpecificationTemplate]));
		w91.Position = 1;
		w91.Expand = false;
		w91.Fill = false;
		// Container child vboxPageTemplates.Gtk.Box+BoxChild
		this.hboxCPMTemplate = new global::Gtk.HBox();
		this.hboxCPMTemplate.Name = "hboxCPMTemplate";
		this.hboxCPMTemplate.Spacing = 6;
		// Container child hboxCPMTemplate.Gtk.Box+BoxChild
		this.alignment7 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment7.Name = "alignment7";
		this.alignment7.LeftPadding = ((uint)(4));
		// Container child alignment7.Gtk.Container+ContainerChild
		this.label14 = new global::Gtk.Label();
		this.label14.WidthRequest = 200;
		this.label14.Name = "label14";
		this.label14.Xalign = 0F;
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Шаблон \"СМР\":");
		this.alignment7.Add(this.label14);
		this.hboxCPMTemplate.Add(this.alignment7);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hboxCPMTemplate[this.alignment7]));
		w93.Position = 0;
		w93.Expand = false;
		w93.Fill = false;
		// Container child hboxCPMTemplate.Gtk.Box+BoxChild
		this.filechooserTemplateCPM = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Шаблон \"СМР\""), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserTemplateCPM.Name = "filechooserTemplateCPM";
		this.hboxCPMTemplate.Add(this.filechooserTemplateCPM);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hboxCPMTemplate[this.filechooserTemplateCPM]));
		w94.Position = 1;
		this.vboxPageTemplates.Add(this.hboxCPMTemplate);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.vboxPageTemplates[this.hboxCPMTemplate]));
		w95.Position = 2;
		w95.Expand = false;
		w95.Fill = false;
		// Container child vboxPageTemplates.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vboxPageTemplates.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vboxPageTemplates[this.hseparator1]));
		w96.Position = 3;
		w96.Expand = false;
		w96.Fill = false;
		// Container child vboxPageTemplates.Gtk.Box+BoxChild
		this.hboxCPMTemplate3 = new global::Gtk.HBox();
		this.hboxCPMTemplate3.Name = "hboxCPMTemplate3";
		this.hboxCPMTemplate3.Spacing = 6;
		// Container child hboxCPMTemplate3.Gtk.Box+BoxChild
		this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment10.Name = "alignment10";
		this.alignment10.LeftPadding = ((uint)(4));
		// Container child alignment10.Gtk.Container+ContainerChild
		this.label17 = new global::Gtk.Label();
		this.label17.WidthRequest = 200;
		this.label17.Name = "label17";
		this.label17.Xalign = 0F;
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Коды ТН ВЭД для группировки:");
		this.alignment10.Add(this.label17);
		this.hboxCPMTemplate3.Add(this.alignment10);
		global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hboxCPMTemplate3[this.alignment10]));
		w98.Position = 0;
		w98.Expand = false;
		w98.Fill = false;
		// Container child hboxCPMTemplate3.Gtk.Box+BoxChild
		this.filechooserIgnoreCodes = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Коды ТН ВЭД для группировки"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserIgnoreCodes.Name = "filechooserIgnoreCodes";
		this.hboxCPMTemplate3.Add(this.filechooserIgnoreCodes);
		global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hboxCPMTemplate3[this.filechooserIgnoreCodes]));
		w99.Position = 1;
		this.vboxPageTemplates.Add(this.hboxCPMTemplate3);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vboxPageTemplates[this.hboxCPMTemplate3]));
		w100.Position = 4;
		w100.Expand = false;
		w100.Fill = false;
		// Container child vboxPageTemplates.Gtk.Box+BoxChild
		this.hboxCPMTemplate2 = new global::Gtk.HBox();
		this.hboxCPMTemplate2.Name = "hboxCPMTemplate2";
		this.hboxCPMTemplate2.Spacing = 6;
		// Container child hboxCPMTemplate2.Gtk.Box+BoxChild
		this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment9.Name = "alignment9";
		this.alignment9.LeftPadding = ((uint)(4));
		// Container child alignment9.Gtk.Container+ContainerChild
		this.label16 = new global::Gtk.Label();
		this.label16.WidthRequest = 200;
		this.label16.Name = "label16";
		this.label16.Xalign = 0F;
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Город отправителя:");
		this.alignment9.Add(this.label16);
		this.hboxCPMTemplate2.Add(this.alignment9);
		global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hboxCPMTemplate2[this.alignment9]));
		w102.Position = 0;
		w102.Expand = false;
		w102.Fill = false;
		// Container child hboxCPMTemplate2.Gtk.Box+BoxChild
		this.entrySenderCity = new global::Gtk.Entry();
		this.entrySenderCity.CanFocus = true;
		this.entrySenderCity.Name = "entrySenderCity";
		this.entrySenderCity.Text = global::Mono.Unix.Catalog.GetString("ДУНИН");
		this.entrySenderCity.IsEditable = true;
		this.entrySenderCity.InvisibleChar = '●';
		this.hboxCPMTemplate2.Add(this.entrySenderCity);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hboxCPMTemplate2[this.entrySenderCity]));
		w103.Position = 1;
		this.vboxPageTemplates.Add(this.hboxCPMTemplate2);
		global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.vboxPageTemplates[this.hboxCPMTemplate2]));
		w104.Position = 5;
		w104.Expand = false;
		w104.Fill = false;
		// Container child vboxPageTemplates.Gtk.Box+BoxChild
		this.hboxCPMTemplate1 = new global::Gtk.HBox();
		this.hboxCPMTemplate1.Name = "hboxCPMTemplate1";
		this.hboxCPMTemplate1.Spacing = 6;
		// Container child hboxCPMTemplate1.Gtk.Box+BoxChild
		this.alignment8 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment8.Name = "alignment8";
		this.alignment8.LeftPadding = ((uint)(4));
		// Container child alignment8.Gtk.Container+ContainerChild
		this.label15 = new global::Gtk.Label();
		this.label15.WidthRequest = 200;
		this.label15.Name = "label15";
		this.label15.Xalign = 0F;
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Номер партии:");
		this.alignment8.Add(this.label15);
		this.hboxCPMTemplate1.Add(this.alignment8);
		global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hboxCPMTemplate1[this.alignment8]));
		w106.Position = 0;
		w106.Expand = false;
		w106.Fill = false;
		// Container child hboxCPMTemplate1.Gtk.Box+BoxChild
		this.entryPartyNumber = new global::Gtk.Entry();
		this.entryPartyNumber.CanFocus = true;
		this.entryPartyNumber.Name = "entryPartyNumber";
		this.entryPartyNumber.Text = global::Mono.Unix.Catalog.GetString("SFHVVO-104/17");
		this.entryPartyNumber.IsEditable = true;
		this.entryPartyNumber.InvisibleChar = '●';
		this.hboxCPMTemplate1.Add(this.entryPartyNumber);
		global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.hboxCPMTemplate1[this.entryPartyNumber]));
		w107.Position = 1;
		this.vboxPageTemplates.Add(this.hboxCPMTemplate1);
		global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vboxPageTemplates[this.hboxCPMTemplate1]));
		w108.Position = 6;
		w108.Expand = false;
		w108.Fill = false;
		// Container child vboxPageTemplates.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.vboxPageTemplates.Add(this.label9);
		global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vboxPageTemplates[this.label9]));
		w109.Position = 7;
		// Container child vboxPageTemplates.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.btnGenerate = new global::Gtk.Button();
		this.btnGenerate.WidthRequest = 80;
		this.btnGenerate.CanFocus = true;
		this.btnGenerate.Name = "btnGenerate";
		this.btnGenerate.UseUnderline = true;
		this.btnGenerate.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
		this.hbox8.Add(this.btnGenerate);
		global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.btnGenerate]));
		w110.PackType = ((global::Gtk.PackType)(1));
		w110.Position = 0;
		w110.Expand = false;
		w110.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.WidthRequest = 80;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Назад");
		this.hbox8.Add(this.button6);
		global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button6]));
		w111.PackType = ((global::Gtk.PackType)(1));
		w111.Position = 1;
		w111.Expand = false;
		w111.Fill = false;
		this.vboxPageTemplates.Add(this.hbox8);
		global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.vboxPageTemplates[this.hbox8]));
		w112.Position = 8;
		w112.Expand = false;
		w112.Fill = false;
		this.stackPages.Add(this.vboxPageTemplates);
		global::Gtk.Notebook.NotebookChild w113 = ((global::Gtk.Notebook.NotebookChild)(this.stackPages[this.vboxPageTemplates]));
		w113.Position = 3;
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Шаблоны");
		this.stackPages.SetTabLabel(this.vboxPageTemplates, this.label1);
		this.label1.ShowAll();
		this.Add(this.stackPages);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 689;
		this.DefaultHeight = 525;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.filechooserTNVED.SelectionChanged += new global::System.EventHandler(this.onTNVEDselected);
		this.filechooserParty.SelectionChanged += new global::System.EventHandler(this.OnPartySelected);
		this.button5.Clicked += new global::System.EventHandler(this.PrevPage);
		this.filechooserTransport.SelectionChanged += new global::System.EventHandler(this.OnTransportSelected);
		this.button7.Clicked += new global::System.EventHandler(this.PrevPage);
		this.button6.Clicked += new global::System.EventHandler(this.PrevPage);
		this.btnGenerate.Clicked += new global::System.EventHandler(this.OnSave);
	}
}
